#!/bin/bash

# This prevents binary error thrown by sed
export LC_CTYPE=C 
export LANG=C
echo "Tip. Initialise git repo first so you can track changes"

echo "Are you in the root folder of Solution?"
read
echo "Warning - will Find and replace recursively from current directory"

# echo "Existing string? e.g. MyProject"
# read existing
existing="ZenMvvm"

echo "Replacement string? e.g. NewProject"
read replacement
echo "Replacing all occurences of $existing with $replacement in files matching $filepattern"

echo "Replacing within files"
find . \( -type d -name .git -prune \) -o -type f -name '*.csproj' -print0 | xargs -0 sed -i '' -e "s/$existing/$replacement/g"
echo "Replacing directory names"
find . -type d -name "*$existing*" | while read FNAME; do mv "$FNAME" "${FNAME//$existing/$replacement}"; done
echo "Replacing file names"
find . -type f -name "*$existing*"  | while read FNAME; do mv "$FNAME" "${FNAME//$existing/$replacement}"; done

echo "Github Organisation/Username? e.g. z33bs"
read organisation
echo "Updating repository URL in project file and main.yml with $organisation"
find . \( -type d -name .git -prune \) -o -type f -name '*.*' -print0 | xargs -0 sed -i '' -e "s/<organization>/$organisation/g"

echo "Whew! All done. Check changes in the versioncontrol."